/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'Webonise' at '3/11/15 3:37 PM' with Gradle 2.3
 *
 * @author Webonise, @date 3/11/15 3:37 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
